#############################################################################
# Makefile for building: DakotaFEM
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  DakotaFEM.pro
# Template: app
# Command: c:\Qt\5.9\fromsource-5.9.0\bin\qmake.exe -o Makefile DakotaFEM.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = c:\Qt\5.9\fromsource-5.9.0\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL_FILE = c:\Qt\5.9\fromsource-5.9.0\bin\qmake.exe -install qinstall file
QINSTALL_PROGRAM = c:\Qt\5.9\fromsource-5.9.0\bin\qmake.exe -install qinstall program
QINSTALL_DIR  = c:\Qt\5.9\fromsource-5.9.0\bin\qmake.exe -install qinstall directory
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: DakotaFEM.pro ..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\win32-msvc\qmake.conf ..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\spec_pre.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\angle.conf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\msvc-desktop.conf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\qconfig.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axbase.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axbase_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axcontainer_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axserver.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axserver_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_dbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designer.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designer_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designercomponents_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_location.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_winextras.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_winextras_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_assimpsceneimport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_defaultgeometryloader.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_dsengine.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_eglvideonode.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfgeometryloader.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfsceneexport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfsceneimport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qdirect2d.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qgif.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qicns.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qico.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qjpeg.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qminimal.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_debugger.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_local.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_messages.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_native.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_nativedebugger.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_profiler.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_server.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qoffscreen.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsgd3d12backend.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsqlite.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsqlodbc.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsvg.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsvgicon.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtaudio_wasapi.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtaudio_windows.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtexttospeech_sapi.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtga.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_esri.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_itemsoverlay.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtiff.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtpeakcanbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_geoclue.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_winrt.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_counterplugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsysteccanbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qttinycanbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtvectorcanbus.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwbmp.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwebp.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwindows.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_scene2d.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_wmfengine.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_xinputgamepad.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\win32-msvc\qmake.conf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\spec_post.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\msvc-version.conf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\toolchain.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\default_pre.prf \
		..\widgets\RandomVariables\RandomVariables.pri \
		..\widgets\Common\Common.pri \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\resolve_config.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\precompile_header.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\resources.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\moc.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\opengl.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\uic.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qmake_use.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\file_copies.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\windows.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exceptions.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\lex.prf \
		DakotaFEM.pro \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\qtmain.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\platforms\qwindows.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qgif.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qicns.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qico.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qjpeg.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qtga.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qtiff.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qwbmp.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qwebp.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Charts.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Widgets.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Gui.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Core.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\libEGL.prl \
		..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\libGLESv2.prl
	$(QMAKE) -o Makefile DakotaFEM.pro
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\spec_pre.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\angle.conf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\msvc-desktop.conf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\qconfig.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_charts.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designer.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_location.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_purchasing.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_assimpsceneimport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_defaultgeometryloader.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_dsengine.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_eglvideonode.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfgeometryloader.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfsceneexport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_gltfsceneimport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qdirect2d.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qgif.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qicns.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qico.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qjpeg.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_debugger.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_local.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_messages.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_native.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_nativedebugger.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_profiler.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_quickprofiler.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_server.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsgd3d12backend.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsqlite.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsqlodbc.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsvg.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtaudio_wasapi.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtexttospeech_sapi.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtga.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_esri.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_itemsoverlay.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_mapbox.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_nokia.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtgeoservices_osm.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtiff.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtpeakcanbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_geoclue.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_serialnmea.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtposition_winrt.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_counterplugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtsysteccanbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qttinycanbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtvectorcanbus.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qtvirtualkeyboardplugin.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwbmp.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwebp.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_scene2d.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_wmfengine.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\modules\qt_plugin_xinputgamepad.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\win32-msvc\qmake.conf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\spec_post.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\common\msvc-version.conf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\toolchain.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\default_pre.prf:
..\widgets\RandomVariables\RandomVariables.pri:
..\widgets\Common\Common.pri:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\resolve_config.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\default_post.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\precompile_header.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qt.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\resources.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\moc.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\opengl.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\uic.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\qmake_use.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\file_copies.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\testcase_targets.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\exceptions.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\yacc.prf:
..\..\..\..\Qt\5.9\fromsource-5.9.0\mkspecs\features\lex.prf:
DakotaFEM.pro:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\qtmain.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\platforms\qwindows.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qgif.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qicns.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qico.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qjpeg.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qtga.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qtiff.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qwbmp.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\plugins\imageformats\qwebp.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Charts.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Widgets.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Gui.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\Qt5Core.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\libEGL.prl:
..\..\..\..\Qt\5.9\fromsource-5.9.0\lib\libGLESv2.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DakotaFEM.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\Users\SimCenter\NHERI\DakotaFEM2\dakotafem_plugin_import.cpp .qmake.stash

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
