abstract: In this example, Bayesian estimation is used to estimate column stiffnesses
  of a simple steel frame, given data about it's mode shapes and mass distribution.
archive: $SIMCENTER_DEV
archive_location: quoFEM/examples/qfem-0008
collection-title: 2-Story Frame
id: qfem-0008
medium: quoFEM
system: quoFEM
title: Bayesian Calibration - Steel Frame
type: book
